from . import property_amenity
from . import property_image
from . import property_building
from . import property_room
from . import property_tenancy
from . import property_document
from . import res_partner
from . import account_move
from . import res_config_settings
