from odoo import _, fields, models


class ResConfigSettings(models.TransientModel):
    _inherit = 'res.config.settings'

    property_default_journal_id = fields.Many2one(
        'account.journal', string='Default Rent Sales Journal',
        config_parameter='msr_property_management.default_journal_id',
        domain="[('type', '=', 'sale')]",
        help='Used for rent invoices when a tenancy does not specify its own sales journal.')
    property_default_product_id = fields.Many2one(
        'product.product', string='Default Rent Product',
        config_parameter='msr_property_management.default_product_id',
        domain="[('sale_ok', '=', True)]",
        help='Proposed by default as the invoicing product on new tenancies.')
    property_auto_post_invoices = fields.Boolean(
        string='Auto-Validate Rent Invoices',
        config_parameter='msr_property_management.auto_post_invoices',
        help='Automatically post rent invoices generated by the recurring invoicing cron, '
             'instead of leaving them in draft for manual review.')
    property_document_reminder_days = fields.Integer(
        string='Document Expiry Reminder (Days)', default=30,
        config_parameter='msr_property_management.document_reminder_days',
        help='Default number of days before a document expiry date to propose on new documents, '
             'and to consider a document "Expiring Soon".')
    property_tenancy_reminder_days = fields.Integer(
        string='Tenancy Expiry Reminder (Days)', default=15,
        config_parameter='msr_property_management.tenancy_reminder_days',
        help='Number of days before a tenancy\'s end date to schedule a reminder activity '
             'for the building\'s property manager.')

    demo_data_loaded = fields.Boolean(string='Demo Data Loaded', compute='_compute_demo_data_loaded')

    def _compute_demo_data_loaded(self):
        loaded = bool(self.env.ref('msr_property_management.demo_building_sunrise', raise_if_not_found=False))
        for record in self:
            record.demo_data_loaded = loaded

    def action_load_property_demo_data(self):
        from odoo.tools.convert import convert_file
        module = self.env['ir.module.module'].sudo().search([('name', '=', 'msr_property_management')], limit=1)
        if not module.demo:
            module.demo = True
        convert_file(self.env, 'msr_property_management', 'demo/property_demo.xml', {}, mode='init')
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Demo Data Loaded'),
                'message': _('Sample buildings, rooms, tenants, tenancies and documents have been created.'),
                'type': 'success',
                'next': {'type': 'ir.actions.client', 'tag': 'reload'},
            },
        }
